packages:
  - 'apps/*'
  - 'packages/*'
  - 'plugins/*'
catalog:
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@types/react': ^18.3.20
  '@types/react-dom': ^18.3.5
  '@types/postcss-import': ^14.0.3
  '@tailwindcss/typography': ^0.5.16
  '@eslint/compat': ^1.2.7
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.23.0
  '@types/node': ^22.13.13
  '@typescript-eslint/eslint-plugin': ^8.28.0
  '@typescript-eslint/parser': ^8.28.0
  eslint: ^9.23.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-prettier: ^5.2.5
  eslint-plugin-react: ^7.37.4
  globals: ^16.0.0
  rimraf: ^6.0.1
  husky: ^9.1.7
  lint-staged: ^15.5.0
  prettier: ^3.5.3
  autoprefixer: ^10.4.21
  cssnano: ^7.0.6
  postcss: ^8.5.3
  postcss-import: ^16.1.0
  postcss-nesting: ^13.0.1
  date-fns: ^4.1.0
  jsencrypt: ^3.3.2
  nanoid: ^5.1.5
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  tailwind-merge: ^3.0.2
  turbo: ^2.4.4
  typescript: ^5.8.2
  clsx: ^2.1.1
  react: ^18.3.1
  react-dom: ^18.3.1
  vite: ^5.4.15
  vitest: ^3.0.9
  tsup: ^8.4.0
